# Default values for acg-front-end.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mariomerco/front-end
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  name: front-end-service

resources:
  {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# REMEMBER TO TEST WHETHER THIS IS REALLY REQUIRED
api:
  url: https://api.devkevinjake.cf/
  resource_api: https://resource-api.devkevinjake.cf/
  inventory_api: https://inventory-api.devkevinjake.cf/
  renting_api: https://renting-api.devkevinjake.cf/
  clients_api: https://clients-api.devkevinjake.cf/
